-- 14. Find the total number of couriers handled by each employee:
SELECT 
    e.EmployeeID, 
    e.Name, 
    COUNT(cea.CourierID) AS TotalCouriersHandled
FROM Employee e
LEFT JOIN CourierEmployeeAssignment cea ON e.EmployeeID = cea.EmployeeID
GROUP BY e.EmployeeID, e.Name;

-- 15. Calculate the total revenue generated by each location:
SELECT 
    l.LocationID, 
    l.LocationName, 
    COALESCE(SUM(p.Amount), 0) AS TotalRevenue
FROM Location l
LEFT JOIN Payment p ON l.LocationID = p.LocationID
GROUP BY l.LocationID, l.LocationName;

-- 16. Find the total number of couriers delivered to each location:
SELECT 
    l.LocationID, 
    l.LocationName, 
    COUNT(DISTINCT c.CourierID) AS CouriersDelivered
FROM Location l
JOIN Courier c ON l.LocationName = SUBSTRING_INDEX(c.ReceiverAddress, ',', 1)
WHERE c.Status = 'Delivered'
GROUP BY l.LocationID, l.LocationName;

-- 17. Find the courier with the highest average delivery time:
SELECT 
    c.CourierID,
    c.TrackingNumber,
    AVG(TIMESTAMPDIFF(HOUR, c.PickupDate, c.DeliveryDate)) AS AvgDeliveryHours
FROM Courier c
WHERE c.Status = 'Delivered' AND c.PickupDate IS NOT NULL AND c.DeliveryDate IS NOT NULL
GROUP BY c.CourierID, c.TrackingNumber
ORDER BY AvgDeliveryHours DESC
LIMIT 1;

-- 18. Find Locations with Total Payments Less Than a Certain Amount (e.g., $1000):
SELECT 
    l.LocationID, 
    l.LocationName, 
    COALESCE(SUM(p.Amount), 0) AS TotalPayments
FROM Location l
LEFT JOIN Payment p ON l.LocationID = p.LocationID
GROUP BY l.LocationID, l.LocationName
HAVING TotalPayments < 1000;

-- 19. Calculate Total Payments per Location:
SELECT 
    l.LocationID, 
    l.LocationName, 
    COALESCE(SUM(p.Amount), 0) AS TotalPayments
FROM Location l
LEFT JOIN Payment p ON l.LocationID = p.LocationID
GROUP BY l.LocationID, l.LocationName;

-- 20. Retrieve couriers who have received payments totaling more than $1000 in a specific location (LocationID = X):
SELECT 
    c.*,
    SUM(p.Amount) AS TotalPayments
FROM Courier c
JOIN Payment p ON c.CourierID = p.CourierID
WHERE p.LocationID = 1  -- Replace with your LocationID
GROUP BY c.CourierID
HAVING TotalPayments > 1000;

-- 21. Retrieve couriers who have received payments totaling more than $1000 after a certain date (PaymentDate > 'YYYY-MM-DD'):
SELECT 
    c.*,
    SUM(p.Amount) AS TotalPayments
FROM Courier c
JOIN Payment p ON c.CourierID = p.CourierID
WHERE p.PaymentDate > '2023-06-01'  -- Replace with your date
GROUP BY c.CourierID
HAVING TotalPayments > 1000;

-- 22. Retrieve locations where the total amount received is more than $5000 before a certain date (PaymentDate > 'YYYY-MM-DD'):
SELECT 
    l.LocationID, 
    l.LocationName, 
    SUM(p.Amount) AS TotalPayments
FROM Location l
JOIN Payment p ON l.LocationID = p.LocationID
WHERE p.PaymentDate < '2023-06-30'  -- Replace with your date
GROUP BY l.LocationID, l.LocationName
HAVING TotalPayments > 5000;